### ISSUE TITLE
justify-content should be changed to 'justify-items' in this article

### ISSUE THREAD

**Issue by ahmarcode** [sanjar-notes/web_dev_fundamentals#90]
https://css-tricks.com/snippets/css/complete-guide-grid/#prop-justify-content

`justify-content: space-between;` didn't work, but `justify-items: center;` worked.

**Comment by ahmarcode** [comment]
Fix the article or fix my understanding

**Comment by ahmarcode** [comment]
My bad. I used `fr` (all remaining space) instead of `auto` (content width). The article is OK.
Here's the code:
```css
#listing {
  display: grid;
  grid-template-columns: repeat(2, auto);
  /* grid-template-columns: repeat(2, 1fr); */
  /* auto means set width to be content width */

  justify-content: space-around;
}
```
The justify-items just "seemed" like it worked.
